# The name of the organisation or entity that owns this project
organisation: "Accellera Systems Initiative"

# A live web address for the organisation
url: "https://www.accellera.org/"

# The default contact email address
email: ""

# The name of the project of books in this folder.
name: "Accellera style guide"

# A one-liner about this project. Useful for Open Graph metadata.
description: "Accellera Systems Initiative is an independent, not-for profit organization dedicated to create, support, promote, and advance system-level design, modeling, and verification standards for use by the worldwide electronics industry. This template, created and maintained by Electric Book Works, is a way to build websites, books and ebooks from the same master content."

# The logo of the organisation, saved web-ready in /assets
logo: "logo.svg"

# An image in /assets/images/web that stands for the project
image: "cover.jpg"

# Credit line, by default in the footer, overidden in locales.yml
credit: "Built with the [Electric Book](https://ebw.co/template)"

# Primary language code for this project as a whole
language: "en"

# App bundle ID unique across all app stores
app-id: com.example.myapp

# Version. You must change this with each app update
version: "1.0.0"
