title: "SystemC Configuration, Control and Inspection Standard"
subtitle: ""
version: "CCI 1.0"
creator: "Accellera Systems Initiative" # E.g. the author
contributor: "" # E.g. other contributors
subject: "TEC008000" # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (https://ns.editeur.org/bic_categories)
description: "This is the SystemC Configuration, Control and Inspection (CCI) Language Reference Manual." # E.g. the blurb
keywords: "Accellera Systems Initiative, SystemC, Configuration, CCI"
publisher: "Accellera Systems Initiative" # E.g. the publisher, imprint or brand name
publisher-url: ""
date: "2018-06-01" # YYYY-MM-DD e.g. publication date
modified: "2018-06-01" # YYYY-MM-DD e.g. date of last revision
type: "Standard" # e.g. Standard, User Guide, Whitepaper
identifier: "" # e.g. ISBN or UUID
source: "" # e.g. parent ISBN or ISTC
language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
relation: "" # e.g. other edition ISBN
coverage: "" # e.g. geographic place or chronological time span
rightsholder: "Accellera" # who owns the copyright?
rights: "All rights reserved." # e.g. a copyright statement
image: "accellera_logo.svg"
status: "Final" # status, e.g., Draft, Final

products: # Metadata for each product for this title (only use values that override parent metadata)
  print-pdf:
    date: "2018-06-01" # YYYY-MM-DD e.g. publication or creation date
    format: "Print" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
    toc:
  screen-pdf:
    date: "2018-06-01" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "0-0-titlepage"
      - "0-1-abstract"
      - "0-2-notice"
      - "0-3-introduction"
      - "0-4-participants"
      - "0-5-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "a"
      - "b"
      - "c"
      - "d"
    toc:
      - file: "01"
        id: "1-overview"
        label: "1. Overview"
        children:
          - file: "01"
            id: "11-scope"
            label: "1.1 Scope"
          - file: "01"
            id: "12-purpose"
            label: "1.2 Purpose"
          - file: "01"
            id: "13-word-usage"
            label: "1.3 Word usage"
            children:
              - file: "01"
                id: "131-relationship-with-c-isoiec-148822011"
                label: "1.3.1 Relationship with C++ (ISO/IEC 14882:2011)"
              - file: "01"
                id: "132-relationship-with-systemc"
                label: "1.3.2 Relationship with SystemC"
              - file: "01"
                id: "133-guidance-for-readers"
                label: "1.3.3 Guidance for readers"
      - file: "02"
        id: "2-normative-references"
        label: "2. Normative references"
      - file: "03"
        id: "3-terminology-and-conventions-used-in-this-standard"
        label: "3. Terminology and conventions used in this standard"
        children:
          - file: "03"
            id: "31-terminology"
            label: "3.1 Terminology"
            children:
              - file: "03"
                id: "311-shall-should-may-can"
                label: "3.1.1 Shall, should, may, can"
              - file: "03"
                id: "312-application-implementation"
                label: "3.1.2 Application, implementation"
              - file: "03"
                id: "313-call-called-from-derived-from"
                label: "3.1.3 Call, called from, derived from"
              - file: "03"
                id: "314-specific-technical-terms"
                label: "3.1.4 Specific technical terms"
          - file: "03"
            id: "32-syntactical-conventions"
            label: "3.2 Syntactical conventions"
            children:
              - file: "03"
                id: "321-implementation-defined"
                label: "3.2.1 Implementation-defined"
              - file: "03"
                id: "322-ellipsis-"
                label: "3.2.2 Ellipsis (…)"
              - file: "03"
                id: "323-class-names"
                label: "3.2.3 Class names"
              - file: "03"
                id: "324-configuration-control-and-inspection-cci-naming-patterns"
                label: "3.2.4 Configuration, Control and Inspection (CCI) naming patterns"
          - file: "03"
            id: "33-typographical-conventions"
            label: "3.3 Typographical conventions"
          - file: "03"
            id: "34-semantic-conventions"
            label: "3.4 Semantic conventions"
            children:
              - file: "03"
                id: "341-class-definitions-and-the-inheritance-hierarchy"
                label: "3.4.1 Class definitions and the inheritance hierarchy"
              - file: "03"
                id: "342-function-definitions-and-side-effects"
                label: "3.4.2 Function definitions and side-effects"
              - file: "03"
                id: "343-exceptions"
                label: "3.4.3 Exceptions"
              - file: "03"
                id: "344-functions-whose-return-type-is-a-reference-or-a-pointer"
                label: "3.4.4 Functions whose return type is a reference or a pointer"
              - file: "03"
                id: "345-functions-that-return-this-or-a-pass-by-reference-argument"
                label: "3.4.5 Functions that return *this or a pass-by-reference argument"
              - file: "03"
                id: "346-functions-that-return-const-char"
                label: "3.4.6 Functions that return const char*"
              - file: "03"
                id: "347-non-compliant-applications-and-errors"
                label: "3.4.7 Non-compliant applications and errors"
              - file: "03"
                id: "348-notes-and-examples"
                label: "3.4.8 Notes and examples"
      - file: "04"
        id: "4-cci-architecture-overview"
        label: "4. CCI architecture overview"
      - file: "05"
        id: "5-configuration-interfaces"
        label: "5. Configuration interfaces"
        children:
          - file: "05"
            id: "51-namespaces"
            label: "5.1 Namespaces"
          - file: "05"
            id: "52-configuration-header-file"
            label: "5.2 Configuration header file"
          - file: "05"
            id: "53-enumerations"
            label: "5.3 Enumerations"
            children:
              - file: "05"
                id: "531-cci_param_mutable_type"
                label: "5.3.1 cci_param_mutable_type"
              - file: "05"
                id: "532-cci_param_data_category"
                label: "5.3.2 cci_param_data_category"
              - file: "05"
                id: "533-cci_name_type"
                label: "5.3.3 cci_name_type"
          - file: "05"
            id: "54-core-interfaces"
            label: "5.4 Core interfaces"
            children:
              - file: "05"
                id: "541-cci_originator"
                label: "5.4.1 cci_originator"
              - file: "05"
                id: "542-cci_param_if"
                label: "5.4.2 cci_param_if"
              - file: "05"
                id: "543-cci_broker_if"
                label: "5.4.3 cci_broker_if"
          - file: "05"
            id: "55-variant-type-parameter-values"
            label: "5.5 Variant type parameter values"
            children:
              - file: "05"
                id: "551-cci_value_category"
                label: "5.5.1 cci_value_category"
              - file: "05"
                id: "552-cci_value"
                label: "5.5.2 cci_value"
              - file: "05"
                id: "553-cci_value_list"
                label: "5.5.3 cci_value_list"
              - file: "05"
                id: "554-cci_value_map"
                label: "5.5.4 cci_value_map"
          - file: "05"
            id: "56-parameters"
            label: "5.6 Parameters"
            children:
              - file: "05"
                id: "561-cci_param_untyped"
                label: "5.6.1 cci_param_untyped"
              - file: "05"
                id: "562-cci_param_typed"
                label: "5.6.2 cci_param_typed"
              - file: "05"
                id: "563-cci_param_untyped_handle"
                label: "5.6.3 cci_param_untyped_handle"
              - file: "05"
                id: "564-cci_param_typed_handle"
                label: "5.6.4 cci_param_typed_handle"
              - file: "05"
                id: "565-cci_param_write_event"
                label: "5.6.5 cci_param_write_event"
          - file: "05"
            id: "57-brokers"
            label: "5.7 Brokers"
            children:
              - file: "05"
                id: "571-cci_broker_handle"
                label: "5.7.1 cci_broker_handle"
              - file: "05"
                id: "572-cci_broker_manager"
                label: "5.7.2 cci_broker_manager"
              - file: "05"
                id: "573-reference-brokers"
                label: "5.7.3 Reference brokers"
          - file: "05"
            id: "58-error-reporting"
            label: "5.8 Error reporting"
          - file: "05"
            id: "59-name-support-functions"
            label: "5.9 Name support functions"
          - file: "05"
            id: "510-version-information"
            label: "5.10 Version information"
      - file: "a"
        id: "annex-a-informative-a-introduction-to-systemc-configuration"
        label: "Annex A (informative) A Introduction to SystemC Configuration"
        children:
          - file: "a"
            id: "a1-sample-code"
            label: "A.1 Sample code"
            children:
              - file: "a"
                id: "a11-basic-parameter-use"
                label: "A.1.1 Basic parameter use"
              - file: "a"
                id: "a12-parameter-handles"
                label: "A.1.2 Parameter handles"
              - file: "a"
                id: "a13-enumerating-parameters"
                label: "A.1.3 Enumerating parameters"
              - file: "a"
                id: "a14-preset-and-default-parameter-values"
                label: "A.1.4 Preset and default parameter values"
              - file: "a"
                id: "a15-linking-parameters-with-callbacks"
                label: "A.1.5 Linking parameters with callbacks"
          - file: "a"
            id: "a2--interface-classes"
            label: "A.2  Interface classes"
            children:
              - file: "a"
                id: "a21-cci_value"
                label: "A.2.1 cci_value"
              - file: "a"
                id: "a22--cci_param"
                label: "A.2.2  cci_param"
              - file: "a"
                id: "a23-cci_param_handle"
                label: "A.2.3 cci_param_handle"
          - file: "a"
            id: "a3-error-reporting"
            label: "A.3 Error reporting"
      - file: "b"
        id: "annex-b-informative-glossary"
        label: "Annex B (informative) Glossary"
      - file: "c"
        id: "annex-c-informative-systemc-configuration-modeler-guidelines"
        label: "Annex C (informative) SystemC Configuration modeler guidelines"
        children:
          - file: "c"
            id: "c1-declare-parameter-instances-as-protected-or-private-members"
            label: "C.1 Declare parameter instances as protected or private members"
          - file: "c"
            id: "c2-initialize-broker-handles-during-module-elaboration"
            label: "C.2 Initialize broker handles during module elaboration"
          - file: "c"
            id: "c3-prefer-typed-parameter-value-access-over-untyped-when-possible-for-speed"
            label: "C.3 Prefer typed parameter value access over untyped, when possible, for speed"
          - file: "c"
            id: "c4-provide-parameter-descriptions"
            label: "C.4 Provide parameter descriptions"
      - file: "d"
        id: "annex-d-informative-enabling-user-defined-parameter-value-types"
        label: "Annex D (informative) Enabling user-defined parameter value types"
